// "use client";

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar";
// import { ThemeProvider } from "@/components/theme-provider";
// import Footer from "@/components/Footer";
// import { usePathname } from "next/navigation";
import ClientLayout from "./ClientLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Supermax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const isAdminRoute = pathname.startsWith("/admin");
  return (
    // <html lang="en" suppressHydrationWarning>
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {/* ✅ ThemeProvider wraps everything */}
    //     <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
    //       {!isAdminRoute && <Navbar />}
    //       {children}
    //       {!isAdminRoute && <Footer />}
    //     </ThemeProvider>
    //   </body>
    // </html>
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
