// "use client";

import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Supermax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const isAdminRoute = pathname.startsWith("/admin");
  return (
    // <html lang="en" suppressHydrationWarning>
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {/* ✅ ThemeProvider wraps everything */}
    //     <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
    //       {!isAdminRoute && <Navbar />}
    //       {children}
    //       {!isAdminRoute && <Footer />}
    //     </ThemeProvider>
    //   </body>
    // </html>
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
         <Providers>
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
